"""
Similarity Engine Module for AI Resume Screening & ATS Score Predictor.
Computes semantic similarity using sentence-transformers/all-MiniLM-L6-v2
and provides TF-IDF cosine similarity as a robust baseline / offline fallback.
"""

import logging
import time
from typing import Dict, List, Optional, Tuple, Union
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Configure logger
logger = logging.getLogger(__name__)

# Check SentenceTransformers availability
try:
    from sentence_transformers import SentenceTransformer
    SBERT_INSTALLED = True
except ImportError:
    SBERT_INSTALLED = False
    logger.warning("sentence-transformers not installed. TF-IDF fallback will be active.")


class SimilarityEngine:
    """
    Production-grade similarity engine offering:
    1. Dense embedding semantic similarity via all-MiniLM-L6-v2
    2. Sparse lexical similarity via TF-IDF & Cosine Similarity
    3. Benchmark comparisons across NLP techniques
    """

    MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"

    def __init__(self, use_sbert: bool = True):
        self.use_sbert = use_sbert and SBERT_INSTALLED
        self._sbert_model = None
        self._tfidf_vectorizer = TfidfVectorizer(
            ngram_range=(1, 2),
            stop_words="english",
            sublinear_tf=True
        )

    @property
    def sbert_model(self):
        """Lazy load the sentence transformer model upon first request."""
        if self.use_sbert and self._sbert_model is None:
            try:
                logger.info(f"Loading SentenceTransformer model '{self.MODEL_NAME}'...")
                self._sbert_model = SentenceTransformer(self.MODEL_NAME)
                logger.info("SentenceTransformer model loaded successfully.")
            except Exception as e:
                logger.error(f"Failed to load SBERT model ({e}). Falling back to TF-IDF.")
                self.use_sbert = False
                self._sbert_model = None
        return self._sbert_model

    def compute_sbert_similarity(self, text_a: str, text_b: str) -> float:
        """
        Computes cosine similarity between dense embeddings of two documents
        generated by sentence-transformers/all-MiniLM-L6-v2.
        """
        model = self.sbert_model
        if model is None:
            # Fallback to TF-IDF
            return self.compute_tfidf_similarity(text_a, text_b)

        if not text_a.strip() or not text_b.strip():
            return 0.0

        try:
            embeddings = model.encode([text_a, text_b], convert_to_numpy=True)
            emb_a = embeddings[0].reshape(1, -1)
            emb_b = embeddings[1].reshape(1, -1)
            sim = float(cosine_similarity(emb_a, emb_b)[0][0])
            return max(0.0, min(1.0, sim))
        except Exception as e:
            logger.error(f"SBERT similarity calculation failed: {e}. Using TF-IDF.")
            return self.compute_tfidf_similarity(text_a, text_b)

    def compute_tfidf_similarity(self, text_a: str, text_b: str) -> float:
        """
        Computes sparse cosine similarity using Sublinear TF-IDF bi-grams.
        """
        if not text_a.strip() or not text_b.strip():
            return 0.0

        try:
            vectorizer = TfidfVectorizer(
                ngram_range=(1, 2),
                stop_words="english",
                sublinear_tf=True
            )
            tfidf_matrix = vectorizer.fit_transform([text_a, text_b])
            sim = float(cosine_similarity(tfidf_matrix[0:1], tfidf_matrix[1:2])[0][0])
            return max(0.0, min(1.0, sim))
        except Exception as e:
            logger.error(f"TF-IDF similarity calculation error: {e}")
            return 0.0

    def compute_jaccard_similarity(self, text_a: str, text_b: str) -> float:
        """
        Computes token-level Jaccard similarity coefficient: |A ∩ B| / |A ∪ B|.
        """
        tokens_a = set(text_a.lower().split())
        tokens_b = set(text_b.lower().split())
        if not tokens_a or not tokens_b:
            return 0.0

        intersection = len(tokens_a.intersection(tokens_b))
        union = len(tokens_a.union(tokens_b))
        return float(intersection / union) if union > 0 else 0.0

    def calculate_similarity(
        self,
        resume_text: str,
        jd_text: str,
        method: str = "sentence_transformer"
    ) -> float:
        """
        Unified similarity interface.
        Methods: 'sentence_transformer', 'tfidf', 'jaccard', 'hybrid'.
        """
        if method == "tfidf":
            return self.compute_tfidf_similarity(resume_text, jd_text)
        elif method == "jaccard":
            return self.compute_jaccard_similarity(resume_text, jd_text)
        elif method == "hybrid":
            # 70% SBERT dense semantic + 30% TF-IDF exact lexical overlap
            sbert_score = self.compute_sbert_similarity(resume_text, jd_text)
            tfidf_score = self.compute_tfidf_similarity(resume_text, jd_text)
            return round(0.7 * sbert_score + 0.3 * tfidf_score, 4)
        else:
            return self.compute_sbert_similarity(resume_text, jd_text)

    def benchmark_comparison(
        self,
        resume_text: str,
        jd_text: str
    ) -> Dict[str, Dict[str, Union[float, str, List[str]]]]:
        """
        Runs empirical benchmarks across TF-IDF, Jaccard, and SBERT,
        measuring latency and similarity metrics.
        """
        results = {}

        # 1. Jaccard Index
        t0 = time.perf_counter()
        jaccard_score = self.compute_jaccard_similarity(resume_text, jd_text)
        t_jaccard = (time.perf_counter() - t0) * 1000

        results["jaccard"] = {
            "method": "Jaccard Token Overlap",
            "latency_ms": round(t_jaccard, 2),
            "similarity_score": round(jaccard_score, 4),
            "description": "Measures raw set-intersection over union of whitespace tokens.",
            "pros": ["Extremely fast (<0.1ms)", "No pre-training required", "Completely deterministic"],
            "cons": ["Zero understanding of synonyms or semantics", "Heavily penalized by vocabulary mismatch"]
        }

        # 2. TF-IDF + Cosine Similarity
        t0 = time.perf_counter()
        tfidf_score = self.compute_tfidf_similarity(resume_text, jd_text)
        t_tfidf = (time.perf_counter() - t0) * 1000

        results["tfidf"] = {
            "method": "TF-IDF + Cosine Similarity",
            "latency_ms": round(t_tfidf, 2),
            "similarity_score": round(tfidf_score, 4),
            "description": "Weighs terms by term-frequency and inverse document frequency, capturing keyword importance.",
            "pros": ["Fast CPU execution", "Accurate for exact keyword tracking", "Handles rare domain terms well"],
            "cons": ["Cannot capture semantic similarity between 'ML' and 'Machine Learning' without exact string matches"]
        }

        # 3. Sentence Transformers (all-MiniLM-L6-v2)
        t0 = time.perf_counter()
        sbert_score = self.compute_sbert_similarity(resume_text, jd_text)
        t_sbert = (time.perf_counter() - t0) * 1000

        results["sentence_transformer"] = {
            "method": "Sentence Transformers (all-MiniLM-L6-v2)",
            "latency_ms": round(t_sbert, 2),
            "similarity_score": round(sbert_score, 4),
            "description": "384-dimensional dense contextual embeddings mapping semantic meaning into metric space.",
            "pros": ["Understands synonyms and paraphrasing", "Captures conceptual qualifications", "Optimal speed/accuracy tradeoff (MiniLM)"],
            "cons": ["Higher latency than TF-IDF (~20-100ms)", "Requires neural network runtime"]
        }

        return results


# Global singleton instance
similarity_engine = SimilarityEngine()
